spring:
  application:
    name: logistics
  main:
    banner-mode: off
  web:
    locale: en
    locale-resolver: fixed
    error:
      include-message: always
      include-binding-errors: always

server:
  port: 8083

event-bridge:
  orchestrator-url: ${ORCHESTRATOR_URL:http://localhost:8080}

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %msg%n"
  level:
    org.springframework: WARN
    org.apache: WARN
